# Generated by Django 6.0.5 on 2026-09-07 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('ONCE', 'Once'), ('INTERVAL', 'Interval'), ('CRON', 'Cron'), ('BENCHMARK', 'Benchmark')], default='IMMEDIATE', max_length=20)),
                ('execute_at', models.DateTimeField(blank=True, null=True)),
                ('every', models.IntegerField(blank=True, null=True)),
                ('period', models.CharField(choices=[('SECONDS', 'Second'), ('MINUTES', 'Minute'), ('HOURS', 'Hour'), ('DAYS', 'Day'), ('WEEKS', 'Week'), ('MONTHS', 'Month')], max_length=20)),
                ('cron', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(default='', max_length=200)),
                ('base_vm_name', models.CharField(default='', max_length=200)),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('status', models.CharField(default='Started', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostgreSQLDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=200)),
                ('encoding', models.CharField(max_length=200)),
                ('collate', models.CharField(max_length=200)),
                ('ctype', models.CharField(max_length=200)),
                ('access_privileges', models.CharField(blank=True, default='', max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('tablespace', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PostgreSQLInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(default=5432)),
                ('version', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PostgreSQLUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostgreSQLBackup',
            fields=[
                ('backupclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='provisioner_api.backupclass')),
                ('backup_type', models.CharField(blank=True, max_length=200, null=True)),
                ('backup_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('stanza', models.CharField(blank=True, max_length=200, null=True)),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('stop_at', models.DateTimeField(auto_now_add=True)),
                ('wal_start', models.CharField(blank=True, max_length=200, null=True)),
                ('wal_stop', models.CharField(blank=True, max_length=200, null=True)),
                ('cluster_size', models.CharField(blank=True, max_length=200, null=True)),
                ('cluster_backup_size', models.CharField(blank=True, max_length=200, null=True)),
                ('backup_size', models.CharField(blank=True, max_length=200, null=True)),
                ('backup_set_size', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=('provisioner_api.backupclass',),
        ),
        migrations.CreateModel(
            name='BackupStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_backups', to='provisioner_api.backupclass')),
            ],
        ),
        migrations.CreateModel(
            name='InfrastructureVM',
            fields=[
                ('vm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='provisioner_api.vm')),
            ],
            bases=('provisioner_api.vm',),
        ),
        migrations.CreateModel(
            name='PostgreSQLVM',
            fields=[
                ('vm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='provisioner_api.vm')),
            ],
            bases=('provisioner_api.vm',),
        ),
        migrations.AddConstraint(
            model_name='vm',
            constraint=models.UniqueConstraint(fields=('vm_name', 'base_vm_name'), name='unique_hostname_constraint'),
        ),
        migrations.AddField(
            model_name='postgresqldatabase',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provisioner_api.postgresqlinstance'),
        ),
        migrations.AddField(
            model_name='postgresqldatabase',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provisioner_api.postgresqluser'),
        ),
        migrations.AddField(
            model_name='postgresqlbackup',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provisioner_api.postgresqlinstance'),
        ),
        migrations.AddField(
            model_name='postgresqlbackup',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='provisioner_api.backupschedule'),
        ),
        migrations.AddField(
            model_name='backupstorage',
            name='infrastructure_vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='provisioner_api.infrastructurevm'),
        ),
        migrations.AddField(
            model_name='postgresqlinstance',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provisioner_api.postgresqlvm'),
        ),
        migrations.AddConstraint(
            model_name='postgresqldatabase',
            constraint=models.UniqueConstraint(fields=('db_name', 'instance'), name='unique_name_instance_owner'),
        ),
        migrations.AddConstraint(
            model_name='backupstorage',
            constraint=models.UniqueConstraint(fields=('backup', 'infrastructure_vm'), name='unique_storage_location'),
        ),
        migrations.AddConstraint(
            model_name='postgresqlinstance',
            constraint=models.UniqueConstraint(fields=('vm', 'port'), name='unique_port_per_vm'),
        ),
    ]
