# Generated by Django 6.0.5 on 2026-07-09 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostgreSQLInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(default=5432)),
                ('version', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PostgreSQLUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostgreSQLBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('stanza', models.CharField(max_length=200)),
                ('start_at', models.DateTimeField()),
                ('stop_at', models.DateTimeField()),
                ('wal_start', models.CharField(max_length=200)),
                ('wal_stop', models.CharField(max_length=200)),
                ('cluster_size', models.CharField(max_length=200)),
                ('cluster_backup_size', models.CharField(max_length=200)),
                ('backup_size', models.CharField(max_length=200)),
                ('backup_set_size', models.CharField(max_length=200)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provisioner_api.postgresqlinstance')),
            ],
        ),
        migrations.CreateModel(
            name='PostgreSQLVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(default='', max_length=200)),
                ('base_vm_name', models.CharField(default='', max_length=200)),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('status', models.CharField(default='Started', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vm_name', 'base_vm_name'), name='unique_hostname_constraint')],
            },
        ),
        migrations.AddField(
            model_name='postgresqlinstance',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provisioner_api.postgresqlvm'),
        ),
        migrations.CreateModel(
            name='PostgreSQLDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=200)),
                ('encoding', models.CharField(max_length=200)),
                ('collate', models.CharField(max_length=200)),
                ('ctype', models.CharField(max_length=200)),
                ('access_privileges', models.CharField(blank=True, default='', max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('tablespace', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provisioner_api.postgresqlinstance')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provisioner_api.postgresqluser')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('db_name', 'instance'), name='unique_name_instance_owner')],
            },
        ),
        migrations.AddConstraint(
            model_name='postgresqlinstance',
            constraint=models.UniqueConstraint(fields=('vm', 'port'), name='unique_port_per_vm'),
        ),
    ]
