# Generated by Django 6.0.5 on 2026-07-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioner_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupschedule',
            name='period',
            field=models.CharField(choices=[('SECONDS', 'Second'), ('MINUTES', 'Minute'), ('HOURS', 'Hour'), ('DAYS', 'Day'), ('WEEKS', 'Week'), ('MONTHS', 'Month')], max_length=20),
        ),
        migrations.AlterField(
            model_name='backupschedule',
            name='schedule_type',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('ONCE', 'Once'), ('INTERVAL', 'Interval'), ('CRON', 'Cron'), ('BENCHMARK', 'Benchmark')], default='IMMEDIATE', max_length=20),
        ),
    ]
