# Generated by Django 6.0.5 on 2026-07-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioner_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgresqlbackup',
            name='type',
        ),
        migrations.AddField(
            model_name='postgresqlbackup',
            name='backup_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='postgresqlbackup',
            name='backup_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='postgresqlbackup',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postgresqlbackup',
            name='backup_set_size',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='postgresqlbackup',
            name='backup_size',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='postgresqlbackup',
            name='cluster_backup_size',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='postgresqlbackup',
            name='cluster_size',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='postgresqlbackup',
            name='stanza',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postgresqlbackup',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postgresqlbackup',
            name='stop_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postgresqlbackup',
            name='wal_start',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='postgresqlbackup',
            name='wal_stop',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
