# Generated by Django 6.0.5 on 2026-07-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioner_api', '0002_remove_postgresqlbackup_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgresqlbackup',
            name='backup_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postgresqlbackup',
            name='backup_set_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postgresqlbackup',
            name='backup_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postgresqlbackup',
            name='cluster_backup_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postgresqlbackup',
            name='cluster_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postgresqlbackup',
            name='wal_start',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postgresqlbackup',
            name='wal_stop',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
