# Generated by Django 6.0.5 on 2026-07-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioner_api', '0003_alter_postgresqlbackup_backup_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgresqlbackup',
            name='execute_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
