name: "Syntax Linting"
on:
  push:
    branches:
      - main
    paths:
      - '**.py'
  workflow_dispatch:
jobs:
  syntax_linting:
    runs-on: ubuntu-latest
    steps:
      - name: "Get Code"
        uses: actions/checkout@v6
      - name: "Install requirements"
        run: |
          pip install -r requirements.txt
      - name: "Perform linting with pylint"
        run: |
          pylint django_rest_api/ --disable=E1101,E0401,R0901,R0903,C0415
          pylint os_executor/os_executor/ --disable=W0613
          pylint os_runner/os_runner/ --disable=W0718
          pylint pg_provisioner/pg_provisioner --disable=R0903
          pylint pg_provisioner_cli/pg_provisioner_cli --disable=W0718,W0613
          pylint pg_runner/pg_runner/
          pylint pg_runner_cli/pg_runner_cli
          pylint os_runner_tester.py
          pylint setup.py
          pylint test.py
      - name: "Perform linting with flake8"
        run: |
          flake8 django_rest_api/
          flake8 os_executor/
          flake8 os_runner/
          flake8 pg_provisioner/
          flake8 pg_provisioner_cli/
          flake8 pg_runner/
          flake8 pg_runner_cli/
          flake8 os_runner_tester.py
          flake8 setup.py
          flake8 test.py